[package]
name = "youtube-playlist-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.*"
google-youtube3 = "5.0.4"
hyper = "1.3.1"
hyper-rustls = "0.27.2"
tokio = { version = "1.38.0", features = ["full"] }
